work_dir: ./work_dir/cyclist

# feeder
feeder: st_gcn.feeder.Feeder_kinetics
train_feeder_args:
  mode: train
  data_path: ./convert-openpose/cyclist_st-gcn_format/train
  label_path : ./convert-openpose/cyclist_labels/train.json
  random_choose: True
  random_move: True
  window_size: 150 
test_feeder_args:
  mode: test 
  data_path: ./convert-openpose/cyclist_st-gcn_format/test
  label_path : ./convert-openpose/cyclist_labels/test.json
  window_size: 150 

# model
model: st_gcn.net.ST_GCN
model_args:
  num_class: 3
  channel: 3
  window_size: 150
  num_person: 2
  num_point: 18
  dropout: 0
  graph: st_gcn.graph.Kinetics
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True
  use_data_bn: True

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [2000, 3000, 4000, 5000]

# training
device: [0,1,2,3]
batch_size: 256
test_batch_size: 256
num_epoch: 6000 
nesterov: True
save_interval: 500



